-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 12:22:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Food_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Food_Item` (
  `Food_ID` INT NOT NULL,
  `Name` VARCHAR(255) NULL,
  `Quantity` INT NULL,
  `Price` DECIMAL NULL,
  PRIMARY KEY (`Food_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Customer` (
  `Customer_ID` INT NOT NULL,
  `Name` VARCHAR(255) NULL,
  `Address` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Staff` (
  `Staff_ID` INT NOT NULL,
  `Name` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Contact_No` VARCHAR(255) NULL,
  `Address` VARCHAR(255) NULL,
  PRIMARY KEY (`Staff_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Order` (
  `Order_ID` INT NOT NULL,
  `Food_Item_Food_ID` INT NOT NULL,
  `Customer_Customer_ID` INT NOT NULL,
  `Staff_Staff_ID` INT NOT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `fk_Order_Food_Item1_idx` (`Food_Item_Food_ID` ASC) VISIBLE,
  INDEX `fk_Order_Customer1_idx` (`Customer_Customer_ID` ASC) VISIBLE,
  INDEX `fk_Order_Staff1_idx` (`Staff_Staff_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Food_Item1`
    FOREIGN KEY (`Food_Item_Food_ID`)
    REFERENCES `LittleLemonDB`.`Food_Item` (`Food_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_Customer_ID`)
    REFERENCES `LittleLemonDB`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Staff1`
    FOREIGN KEY (`Staff_Staff_ID`)
    REFERENCES `LittleLemonDB`.`Staff` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Order_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Order_Item` (
  `Quantity` INT NULL,
  `Unit_Price` DECIMAL NULL,
  `Order_Order_ID` INT NOT NULL,
  `Food_Item_Food_ID` INT NOT NULL,
  INDEX `fk_Order_Item_Order_idx` (`Order_Order_ID` ASC) VISIBLE,
  PRIMARY KEY (`Order_Order_ID`),
  INDEX `fk_Order_Item_Food_Item1_idx` (`Food_Item_Food_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Item_Order`
    FOREIGN KEY (`Order_Order_ID`)
    REFERENCES `LittleLemonDB`.`Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Item_Food_Item1`
    FOREIGN KEY (`Food_Item_Food_ID`)
    REFERENCES `LittleLemonDB`.`Food_Item` (`Food_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Booking` (
  `Booking_ID` INT NOT NULL,
  `Date` DATE NULL,
  `Time` TIME NULL,
  `No_of_Customers` INT NULL,
  `Customer_Customer_ID` INT NOT NULL,
  `Staff_Staff_ID` INT NOT NULL,
  PRIMARY KEY (`Booking_ID`),
  INDEX `fk_Booking_Customer1_idx` (`Customer_Customer_ID` ASC) VISIBLE,
  INDEX `fk_Booking_Staff1_idx` (`Staff_Staff_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Booking_Customer1`
    FOREIGN KEY (`Customer_Customer_ID`)
    REFERENCES `LittleLemonDB`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Staff1`
    FOREIGN KEY (`Staff_Staff_ID`)
    REFERENCES `LittleLemonDB`.`Staff` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Payment` (
  `Pay_ID` INT NOT NULL,
  `amount` DECIMAL NULL,
  `date` DATE NULL,
  `Order_Order_ID` INT NOT NULL,
  PRIMARY KEY (`Pay_ID`, `Order_Order_ID`),
  INDEX `fk_Payment_Order1_idx` (`Order_Order_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Order1`
    FOREIGN KEY (`Order_Order_ID`)
    REFERENCES `LittleLemonDB`.`Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Delivery` (
  `Delivery_ID` INT NOT NULL,
  `Date` DATE NULL,
  `Status` TINYINT NULL,
  `Payment_Pay_ID` INT NOT NULL,
  `Payment_Order_Order_ID` INT NOT NULL,
  PRIMARY KEY (`Delivery_ID`),
  INDEX `fk_Delivery_Payment1_idx` (`Payment_Pay_ID` ASC, `Payment_Order_Order_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Delivery_Payment1`
    FOREIGN KEY (`Payment_Pay_ID` , `Payment_Order_Order_ID`)
    REFERENCES `LittleLemonDB`.`Payment` (`Pay_ID` , `Order_Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
